# Generated by Django 4.1.3 on 2022-12-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='Listing',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Listing',
            new_name='listing',
        ),
    ]
