# Generated by Django 4.1.3 on 2022-12-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_listing_bid_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='open_forbid',
            field=models.BooleanField(default=True),
        ),
    ]
